openapi: 3.0.2
info:
  title: ventas
  version: 1.0.0
  description: API encargada de resolver la integración con SAP para ventas.
servers:
  -
    url: ventas.tarjeta-copec-poc.svc.cluster.local
    description: ''
paths:
  /tarjetas-combustible:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/transaccion'
        required: true
      tags:
        - Operaciones
      responses:
        '202':
          description: La solicitud se a recibido correctamente.
      operationId: tarjetaCombustible
      summary: tarjetas-combustible
      description: >-
        Operación que permite la integración con SAP para registrar la venta con tarjetas TAE (Tarjeta
        de Abastecimiento en Empresa) y TCT (Tarjeta Copec de Transporte).
  /tarjetas-combustible-callback:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/estado-transaccion'
        required: true
      tags:
        - Operaciones
      responses:
        '202':
          description: La solicitud se a recibido correctamente.
      summary: tarjetas-combustible-callback
      description: >-
        Operación que permite a SAP responder el resultado del registro de la venta  con tarjeta TAE o
        TCT.
components:
  schemas:
    detalle:
      title: Root Type for detalle
      description: ''
      type: object
      properties:
        producto:
          $ref: '#/components/schemas/producto'
          properties:
            codigo:
              type: string
            tipo:
              type: string
            precio-unitario:
              format: int32
              type: integer
        cantidad:
          description: Cantidad vendida del producto
          type: integer
        unidad-de-medida:
          description: Unidad con la que se mide el producto
          type: string
      example:
        producto:
          codigo: '000000000000000013'
          tipo: COMB
          precio-unitario: 878
        cantidad: 70
        unidad-de-medida: L
    producto:
      title: Root Type for producto
      description: ''
      type: object
      properties:
        codigo:
          description: Código del producto
          type: string
        tipo:
          description: Tipo del producto
          type: string
        precio-unitario:
          format: int32
          description: Valor unitario del producto
          type: integer
      example:
        codigo: '000000000000000013'
        tipo: COMB
        precio-unitario: 878
    entrega:
      title: Root Type for entrega
      description: ''
      type: object
      properties:
        tipo:
          description: Tipo de entrega
          type: string
        descripcion:
          description: Descripción del tipo de entrega
          type: string
        costo-flete:
          description: Costo del flete asociado a la operación si corresponde
          type: integer
      example:
        tipo: R
        descripcion: '00'
        costo-flete: 0
    estado-transaccion:
      title: Root Type for estado-transaccion
      description: ''
      type: object
      properties:
        id:
          format: int32
          description: Identificador de la transacción
          type: integer
        pedido:
          description: Numero de pedido con que se registra la transacción en SAP
          type: string
        posicion:
          format: int32
          description: Posición dentro del pedido
          type: integer
        comentarios:
          description: Información del error funcional
          type: string
        monto-comision:
          format: int32
          description: Comisión de la estación
          type: integer
        comision-flete:
          format: int32
          description: Comisión del flete
          type: integer
        descuento:
          format: int32
          description: Monto en pesos de descuento
          type: integer
        condicion-precio:
          description: Tipo de acuerdo de precio
          type: string
      example:
        id: 12345
        pedido: 0368304912
        posicion: 10
        comentarios: ''
        monto-comision: 490
        comision-flete: 0
        descuento: 1750
        condicion-precio: D08
    guia-despacho:
      title: Root Type for guia-despacho
      description: ''
      type: object
      properties:
        folio:
          description: Número de la guía de despacho
          type: string
      example:
        folio: 000010860361
    problem:
      description: ''
      type: object
      properties:
        detail:
          description: A human readable explanation specific to this occurrence of the problem.
          type: string
        instance:
          format: uri
          description: >-
            An absolute URI that identifies the specific occurrence of the problem. It may or may
            not yield further information if dereferenced.
          type: string
        status:
          format: int32
          description: >-
            The HTTP status code generated by the origin server for this occurrence of the
            problem.
          type: integer
        title:
          description: >-
            A short, summary of the problem type. Readable for engineers (usually not suited for
            non technical stakeholders and not localized); example: Service Unavailable
          type: string
        type:
          format: uri
          description: >-
            An absolute URI that identifies the problem type.  When dereferenced, it SHOULD
            provide human-readable documentation for the problem type (e.g., using HTML).
          type: string
    tarjeta:
      title: Root Type for tarjeta
      description: ''
      type: object
      properties:
        numero:
          description: Número de tarjeta
          type: string
        tipo:
          description: Tipo de tarjeta
          type: string
      example:
        numero: '00120'
        tipo: TAE
    vehiculo:
      title: Root Type for vehiculo
      description: ''
      type: object
      properties:
        patente:
          description: Patente del vehículo
          type: string
        odometro:
          description: Kilometraje actual del vehículo
          type: string
        tipo:
          description: Tipo de vehículo
          type: string
        correlativo:
          description: Correlativo del vehículo del cliente
          type: string
      example:
        patente: CC 260
        odometro: '0000000'
        tipo: '12'
        correlativo: '0020'
    venta:
      title: Root Type for venta
      description: ''
      type: object
      properties:
        detalle:
          type: array
          items:
            $ref: '#/components/schemas/detalle'
        precio-total:
          description: Valor total de la venta
          type: number
      example:
        detalle:
          -
            producto:
              codigo: '000000000000000013'
              tipo: COMB
              precio-unitario: 878
            cantidad: 70
            unidad-de-medida: L
        precio-total: 61460
    transaccion:
      title: Root Type for transaccion
      description: ''
      type: object
      properties:
        id:
          description: Identificador de la transacción
          type: integer
        solicitante:
          description: Código de la persona que solicita la operación
          type: string
        numero-rollo-voucher:
          description: Número de rollo asociado al voucher emitido
          type: string
        fecha:
          description: Fecha de la operación
          type: string
        hora:
          description: Hora de la operación
          type: string
        validacion-anillo:
          description: Estado de la validación del anillo
          type: string
        condicion-precio:
          description: Tipo de acuerdo de precio
          type: string
        estado-vigencia:
          description: Estado de vigencia de la transacción que permite anularla
          type: string
        firma-electronica:
          description: Código de firma electrÃ³nica del documento legal
          type: string
        orden-compra-cliente:
          description: Orden de compra de los clientes fiscales
          type: string
        tarjeta:
          $ref: '#/components/schemas/tarjeta'
          properties:
            numero:
              type: string
            tipo:
              type: string
        eds:
          $ref: '#/components/schemas/eds'
          properties:
            codigo:
              type: string
        guia-despacho:
          $ref: '#/components/schemas/guia-despacho'
          properties:
            folio:
              type: string
        vehiculo:
          $ref: '#/components/schemas/vehiculo'
          properties:
            patente:
              type: string
            odometro:
              type: string
            tipo:
              type: string
            correlativo:
              type: string
        venta:
          $ref: '#/components/schemas/venta'
          properties:
            detalle:
              type: array
              items:
                type: object
                properties:
                  producto:
                    type: object
                    properties:
                      codigo:
                        type: string
                      tipo:
                        type: string
                      precio-unitario:
                        format: int32
                        type: integer
                  cantidad:
                    format: int32
                    type: integer
                  unidad-de-medida:
                    type: string
            precio-total:
              format: int32
              type: integer
        entrega:
          $ref: '#/components/schemas/entrega'
          properties:
            tipo:
              type: string
            descripcion:
              type: string
            costo-flete:
              format: int32
              type: integer
      example:
        id: 12345
        solicitante: 0000663287
        numero-rollo-voucher: '000000000001'
        fecha: '20220304'
        hora: '71600'
        validacion-anillo: ''
        condicion-precio: T02
        estado-vigencia: ''
        firma-electronica: GE|<CAF version="1.0"><DA><RE>99520000-7</RE><RS>COPEC S.A.</RS>
        orden-compra-cliente: '0'
        tarjeta:
          numero: '00120'
          tipo: TAE
        eds:
          codigo: 0000010197
        guia-despacho:
          folio: 000010860361
        vehiculo:
          patente: CC 260
          odometro: '0000000'
          tipo: '12'
          correlativo: '0020'
        venta:
          detalle:
            -
              producto:
                codigo: '000000000000000013'
                tipo: COMB
                precio-unitario: 878
              cantidad: 70
              unidad-de-medida: L
          precio-total: 61460
        entrega:
          tipo: R
          descripcion: '00'
          costo-flete: 0
    eds:
      title: Root Type for codigo
      description: ''
      type: object
      properties:
        codigo:
          description: Identificador de una estación de servicio
          type: string
      example:
        codigo: 0000010197
tags:
  -
    name: Estado
    description: Diseño
  -
    name: Tipo
    description: Técnica
